# Create a new user
POST http://localhost:3000/api/blog-users/register HTTP/1.1
Content-Type: application/json

{
  "email": "ussesa2sre2r@notfound.local",
  "avatar": "asdasd.png",
  "userName": "Smith",
  "password": "123456"
}

###

# Update a user by id
PATCH http://localhost:3000/api/blog-users/65925a35aef11c5b4ecc0e45 HTTP/1.1
Content-Type: application/json

{
  "userName": "Smizxfcvzxth"
}

###

###
# Get user by ID
GET http://localhost:3000/api/blog-users/65925a35aef11c5b4ecc0e45 HTTP/1.1

###

###
# Get user by email
GET http://localhost:3000/api/blog-users/email/ussesa2sre2r@notfound.local HTTP/1.1

###

# Get all users
GET http://localhost:3000/api/blog-users HTTP/1.1

###

# Delete user by id
DELETE http://localhost:3000/api/blog-users/087f8ffc-3550-4294-9549-beba37ed641e HTTP/1.1

###
