# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "userr@notfound.local",
  "avatar": "asdasd.png",
  "userName": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/d7f8f479-d5b0-489a-8072-026e2edf049e HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "userr@notfound.local",
  "password": "123456"
}

###
